### ISSUE TITLE
Error on npm build

### ISSUE THREAD

**Issue by 10polarbears** [simiancraft/BabylonJs-Editor-Workflow-Boilerplate#2]
After following you Workflow Boilerplate approach.

I keep getting these errors when running npm build following 261 other errors.
Is there somewhere I can start looking to fix this?

If I continue an run the location server quite often the files test out fine. However when I attempt to run them from my server they can quite often fail when trying to import texture files.

Any help at all would be appreciated. Unfortunately I don't seem t know what I am doing.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! babylonjs-editor-generated-template@0.0.1 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the babylonjs-editor-generated-template@0.0.1 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/trevorcoates/.npm/_logs/2019-08-06T08_28_31_781Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! babylonjs-editor-generated-template@0.0.1 build: `npm run clean && npm run compile`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the babylonjs-editor-generated-template@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by the-simian** [comment]
@10polarbears , can you check out that debug-log that got written? looks like there's a problem with a dependency maybe

**Comment by 10polarbears** [comment]
Thank you for your response. Here is the log. It appears that the Babylon template has issues.
The Babylon support forum address has been archived.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile'
1 verbose cli ]
2 info using npm@6.10.0
3 info using node@v12.7.0
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle babylonjs-editor-generated-template@0.0.1~precompile: babylonjs-editor-generated-template@0.0.1
6 info lifecycle babylonjs-editor-generated-template@0.0.1~compile: babylonjs-editor-generated-template@0.0.1
7 verbose lifecycle babylonjs-editor-generated-template@0.0.1~compile: unsafe-perm in lifecycle true
8 verbose lifecycle babylonjs-editor-generated-template@0.0.1~compile: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Work_RAID/604_webGL_learning/web-project/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/Work_RAID/604_webGL_learning/web-project/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
9 verbose lifecycle babylonjs-editor-generated-template@0.0.1~compile: CWD: /Volumes/Work_RAID/604_webGL_learning/web-project
10 silly lifecycle babylonjs-editor-generated-template@0.0.1~compile: Args: [ '-c', 'tsc -p .' ]
11 silly lifecycle babylonjs-editor-generated-template@0.0.1~compile: Returned: code: 2  signal: null
12 info lifecycle babylonjs-editor-generated-template@0.0.1~compile: Failed to exec compile script
13 verbose stack Error: babylonjs-editor-generated-template@0.0.1 compile: `tsc -p .`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid babylonjs-editor-generated-template@0.0.1
15 verbose cwd /Volumes/Work_RAID/604_webGL_learning/web-project
16 verbose Darwin 17.7.0
17 verbose argv "/usr/local/Cellar/node/12.7.0/bin/node" "/usr/local/bin/npm" "run" "compile"
18 verbose node v12.7.0
19 verbose npm  v6.10.0
20 error code ELIFECYCLE
21 error errno 2
22 error babylonjs-editor-generated-template@0.0.1 compile: `tsc -p .`
22 error Exit status 2
23 error Failed at the babylonjs-editor-generated-template@0.0.1 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]


Sample of 261 errors reported in Terminal.

node_modules/babylonjs-editor/node_modules/babylonjs/babylon.module.d.ts:37275:9 - error TS2416: Property '_getViewMatrix' in type 'ArcRotateCamera' is not assignable to the same property in base type 'TargetCamera'.
  Type '() => import("babylonjs/Maths/math.vector").Matrix' is not assignable to type '() => import("babylonjs/Maths/math").Matrix'.
    Type 'import("babylonjs/Maths/math.vector").Matrix' is not assignable to type 'import("babylonjs/Maths/math").Matrix'.

37275         _getViewMatrix(): Matrix;

**Comment by the-simian** [comment]
quick question: was this with the projects in this actual repo, or was this with a freshly templated version of the editor?
`Property '_getViewMatrix' in type 'ArcRotateCamera' is not assignable to the same property in base type 'TargetCamera'.`

it appears there's some issue related to the camera. I think at this point I'd need to try pulling and running myself, and determining if its a bug in the more recent version of the Editor or the templated issues in this repo.

Did you download the Editor and follow the tutorial or get this error with the projects in here? Thanks for checking. I won't be able to look for some time, myself


also: did you get a browser to pop up? was there anything in the console? this all helps me figure it out

**Comment by 10polarbears** [comment]
Hi there,



> On 8 Aug 2019, at 6:01 am, Jesse Harlin <notifications@github.com> wrote:
> 
> quick question: was this with the projects in this actual repo, or was this with a freshly templated version of the editor?
> Property '_getViewMatrix' in type 'ArcRotateCamera' is not assignable to the same property in base type 'TargetCamera'.
> 

This issue that has been identified here is just one example error of the 261 errors of a similar type (see below for 5 more randomly selected errors).
The errors start I believe because there are issues with the template.

> it appears there's some issue related to the camera. I think at this point I'd need to try pulling and running myself, and determining if its a bug in the more recent version of the Editor or the templated issues in this repo.
> 
> Did you download the Editor and follow the tutorial or get this error with the projects in here? Thanks for checking. I won't be able to look for some time, myself
> 

I downloaded the latest stable version of the editor to work locally. Then rebuilt the Boilerplate example using the Rainy Day files and some of my own exported from Maya. Creating a new template from these files as two new scenes. What I haven’t done is build and run the Boilerplate files as downloaded using there template set up.

The template is newly created with the current version of the editor. It does look to me to be the new template causing the issues not anything in the Boilerplate files.

The new template will run under a local server but not from a webserver.

I have however been able to strip out my files from the project and just using just the Rainy Day files build a new template.
This new template still generates the errors on build however I have taken it successfully through local server and web server delivery.

http://www.leapfrog.net.au/client/webGL/web-test/index.html



BTW:
Thank you very much for your work on setting up the Boilerplate exercise. I have learnt a lot from it.

Trev


node_modules/babylonjs/babylon.module.d.ts:53895:9 - error TS2416: Property 'removeDragGradient' in type 'GPUParticleSystem' is not assignable to the same property in base type 'IParticleSystem'.
  Type '(gradient: number) => GPUParticleSystem' is not assignable to type '{ (gradient: number): IParticleSystem; (gradient: number): IParticleSystem; }'.
    Type 'GPUParticleSystem' is not assignable to type 'IParticleSystem'.

53895         removeDragGradient(gradient: number): GPUParticleSystem;
              ~~~~~~~~~~~~~~~~~~

node_modules/babylonjs/babylon.module.d.ts:53969:9 - error TS2416: Property 'getRampGradients' in type 'GPUParticleSystem' is not assignable to the same property in base type 'IParticleSystem'.
  Type '() => Color3Gradient[]' is not assignable to type '{ (): Color3Gradient[]; (): Color3Gradient[]; }'.

53969         getRampGradients(): Nullable<Array<Color3Gradient>>;
              ~~~~~~~~~~~~~~~~

node_modules/babylonjs/babylon.module.d.ts:54045:9 - error TS2416: Property 'clone' in type 'GPUParticleSystem' is not assignable to the same property in base type 'IParticleSystem'.
  Type '(name: string, newEmitter: any) => GPUParticleSystem' is not assignable to type '{ (name: string, newEmitter: any): IParticleSystem; (name: string, newEmitter: any): IParticleSystem; }'.
    Type 'GPUParticleSystem' is not assignable to type 'IParticleSystem'.

54045         clone(name: string, newEmitter: any): GPUParticleSystem;
              ~~~~~

node_modules/babylonjs/babylon.module.d.ts:105077:18 - error TS2420: Class 'PBRMaterialDefines' incorrectly implements interface 'IMaterialSubSurfaceDefines'.
  Property 'SS_LINEARSPECULARREFRACTION' is missing in type 'PBRMaterialDefines' but required in type 'IMaterialSubSurfaceDefines'.

105077     export class PBRMaterialDefines extends MaterialDefines implements IImageProcessingConfigurationDefines, IMaterialClearCoatDefines, IMaterialAnisotropicDefines, IMaterialBRDFDefines, IMaterialSheenDefines, IMaterialSubSurfaceDefines {
                        ~~~~~~~~~~~~~~~~~~

  node_modules/babylonjs-editor/node_modules/babylonjs/babylon.module.d.ts:109586:9
    109586         SS_LINEARSPECULARREFRACTION: boolean;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'SS_LINEARSPECULARREFRACTION' is declared here.

**Comment by the-simian** [comment]
there's a lot of moving parts in your description and lets take it one step at a time, if that's ok. You're talking about importing things from Maya, local servers, remote servers, I see typescript errors too. There's so many moving parts, I'm not zeroing in on what might be your issue. My first thought is that you're having some kind of typescript error or something, because these all seem primarily to be ts thrown.

@10polarbears just to cover our bases: can you clone this: https://github.com/simiancraft/BabylonJs-Editor-Workflow-Boilerplate/tree/master/web-project

and run it locally? I don't mean generating from your editor, but just clone, npm install and run (locally).

**Comment by 10polarbears** [comment]
Hi Jesse,



When I go to that URL there is no button for cloning or downloading available.

**Comment by 10polarbears** [comment]
Hi Jesse,


I have however downloaded it from here https://github.com/simiancraft/BabylonJs-Editor-Workflow-Boilerplate
I am hoping that it is the same thing.



Thank you.
Trev

**Comment by the-simian** [comment]
@10polarbears yes, that's the generated web project that I used when making the tutorial

**Comment by 10polarbears** [comment]
I am running now.

This came up so I updated


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New patch version of npm available! 6.10.0 → 6.10.3       │
   │   Changelog: https://github.com/npm/cli/releases/tag/v6.10.3   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

192-168-1-50:BabylonJs-Editor-Workflow-Boilerplate-master trevorcoates$ npm installl -g npm

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /Users/trevorcoates/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.10.0 /usr/local/lib/node_modules/npm

Did you mean one of these?
    install
    uninstall
    unstar

**Comment by 10polarbears** [comment]
Hi Jesse


run install

192-168-1-50:web-project trevorcoates$ npm install
npm WARN deprecated ecstatic@1.4.1: https://github.com/jfhbrook/node-ecstatic/issues/259
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN babylonjs-editor-generated-template@0.0.1 No repository field.

updated 52 packages and audited 59 packages in 10.053s
found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
192-168-1-50:web-project trevorcoates$ 

run build – no errors

192-168-1-50:web-project trevorcoates$ npm run build

> babylonjs-editor-generated-template@0.0.1 build /Volumes/Work_RAID/604_webGL_learning/errorTesting/BabylonJs-Editor-Workflow-Boilerplate-master/web-project
> npm run clean && npm run compile


> babylonjs-editor-generated-template@0.0.1 clean /Volumes/Work_RAID/604_webGL_learning/errorTesting/BabylonJs-Editor-Workflow-Boilerplate-master/web-project
> rimraf .build && rimraf .declaration && rimraf build && rimraf declaration


> babylonjs-editor-generated-template@0.0.1 compile /Volumes/Work_RAID/604_webGL_learning/errorTesting/BabylonJs-Editor-Workflow-Boilerplate-master/web-project
> tsc -p .

192-168-1-50:web-project trevorcoates$ 

run webserver

192-168-1-50:web-project trevorcoates$ npm run webserver

> babylonjs-editor-generated-template@0.0.1 webserver /Volumes/Work_RAID/604_webGL_learning/errorTesting/BabylonJs-Editor-Workflow-Boilerplate-master/web-project
> http-server -p 1338 -c-1

Starting up http-server, serving ./
Available on:
  http://127.0.0.1:1338
  http://192.168.1.50:1338
  http://192.168.2.1:1338
Hit CTRL-C to stop the server


Runs fine locally.

**Comment by the-simian** [comment]
no sweat, that's just a typo: You have 3 l's in the word 'install.

Also, I hate to bother you about this, but can you stop replying by email, because it is making a lot of noise in this thread issue, such as including previous items in the thread as well as your confidentiality clause, etc. (Please be aware we are posting in a public thread at the moment)

I'll be happy to help, try copying and pasting from the readme for the commands too, if you're unsure about spelling.

I see the project runs ok, so I think the issue might be your environment and typescript setup, so I'm closing the issue for now. If someone else has a problem and references this issue I'll reopen

**Comment by 10polarbears** [comment]
Apologies for the noise.

Works just fine from web server also.

**Comment by 10polarbears** [comment]
Here is the main discrepancy:

package.json – seems to have the main difference

The editor uses: "http-server": "^0.11.1"

 "license": "(Apache-2.0)",
  "devDependencies": {
    "@types/systemjs": "0.20.6",
    "@types/javascript-astar": "~0.0.30",
    "typescript": "~3.5.1",
    "http-server": "^0.11.1"

Whereas the GitHub version uses: "http-server": "^0.9.0"

  "license": "(Apache-2.0)",
  "devDependencies": {
    "@types/systemjs": "0.20.6",
    "@types/javascript-astar": "~0.0.30",
    "typescript": "~3.5.1",
    "http-server": "^0.9.0"

**Comment by the-simian** [comment]
@10polarbears you know what? I seem to recall http-server was broken for me too now that you mention it. https://github.com/http-party/http-server/issues/534

I tried upgrading and had to downgrade. It was a really challenging issue for me! If you manged to figure that out, seriously - pat yourself on the back. It was hard. I know because you've jogged my own memory and I remember it.

At some point I just need to change that to webpack and submit a PR to Julian, which I think he'd appreciate.

Thanks for the followup and seriously, GOOD JOB!

**Comment by 10polarbears** [comment]
Thank you.

I am finding the whole editor thing quite a stumbling block. Things don't seem to work properly. eg trying to find a DDS format that will actually import is practically impossible. When you do the files sizes explode. 
When you watch the out-of-date tutorials there is a section where you select the scene then choose the View>Code function where looks a breeze in V2 but in V3 nothing but an empty window.
I am sure the deeper I look into the editor the more confused I am likely to become.

**Comment by 10polarbears** [comment]
The full list of manual depreciation:
@game.ts
  const "name of babylonFile" = `./scene/`;
    let currentScene = "name of babylonFile";

    SceneLoader.Load(
      `${currentScene}`,
      "scene.babylon",
      this.engine,
      (scene: Scene) => {
        this.scene = scene;
        console.log(this.scene);

@package.json
    "typescript": "~3.5.1",
    "http-server": "^0.9.0"

    "babylonjs-editor": "3.1.1",
    "cannon": "~0.6.2",

**Comment by 10polarbears** [comment]
This is so hit and miss. In my web server I now get:

It would appear the editor isn't quite yet ready for webGL 2.

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (favicon.ico, line 0)
[Log] Babylon.js v4.0.3 - WebGL1
[Log] Scene {rootNodes: Array, cameras: Array, lights: Array, meshes: Array, skeletons: [], …}
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (montrealenvmapmedEnvHDR.dds, line 0)
[Warning] BJS - [12:58:27]: _DDSTextureLoader failed when trying to load ./scene/montrealenvmapmedEnvHDR.dds, falling back to the next supported loader
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (hughanPot_final_01.jpg, line 0)
[Error] BJS - [12:58:27]: Error while trying to load image: ./scene/hughanPot_final_01.jpg
	_ErrorEnabled (babylon.max.js:106123)
	errorHandler (babylon.max.js:110188)

**Comment by the-simian** [comment]
@10polarbears if you're finding issues, you might go to the Editor's main git repo, this is just a repo for the boilerplate I made. If you carefully log issues, Julian is very responsive.
